name: update All issue to project

on:
  issues:
    types:
      - opened
jobs:
  add-to-project:
    name: Add To GitHub projects
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@RELEASE_VERSION
        with:
          # URL of the project to add issues to
          project-url: https://github.com/orgs/radiosport-live/projects/1
          # A GitHub personal access token with write access to the project
          github-token: ${{secrets.ADD_TO_PROJECT_PAT}}
