name: update All issue to project

on:
  push:
     branches: [master]
  issues:
    types: 
      - opened
    
jobs:
  add-to-project:
    name: Add To GitHub projects
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.5.1
        with: 
          node-version: 16.x
          cache: npm
          
      - name: Run Contest script
        run: bash ./contesting_script.sh <<!
            y
            y
            n
            !
        
